// Generated by .github/workflows/ci.yml from the SUBMISSION_SHEET_PROD
// secret on every push to main — do not hand-edit, it will be overwritten.
// For local development against the test sheet, copy js/env.local.example.js
// to js/env.local.js (gitignored) and submit.js will prefer it instead.
export const ENV = {
  SUBMISSION_ENDPOINT: "https://script.google.com/macros/s/AKfycbwmAlpt-VjmBtEI5Za2LfGMvywgAjgveFCnPLpgwk7VxRHjyswvS_sQyRP7p-mNhSJH/exec",
};
